# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2
      - run: mkdir -p dist  # Certifique-se de que a pasta existe

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: EvaAnanias
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: ls -la dist
      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # Atualize para a última versão estável
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master  # Altere para `main` se for a sua branch principal
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
